// Code generated by github.com/julienstroheker/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func TestCosmosdb(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Cosmosdb Suite")
}
